### ISSUE TITLE
14/09 - Team94

### ISSUE THREAD

**Issue by idgm5** [FrancoRosa/cloud-wars#1]
Any comments or suggestions, please add them here.

**Comment by ferbaco86** [comment]
Cool game Franco!

There are some bugs that I found:
- I don't die when I get hit by the enemies lasers, the lives counter goes to negative values(see screenshot)
- The ship goes out of the screen(see screenshot)
- The tab name is still showing AlienWars instead of your new name CloudWars
![capturaCloudWars](https://user-images.githubusercontent.com/52765379/93100588-b3709200-f67f-11ea-948b-9383e99aa163.png)

**Comment by FrancoRosa** [comment]
Thank you for the feedback
Those issues are already fixed
